# Generated by Django 4.2.6 on 2023-10-12 07:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todomodel',
            name='dateTime',
        ),
        migrations.AddField(
            model_name='todomodel',
            name='date',
            field=models.DateField(default=datetime.date(2023, 10, 12)),
        ),
        migrations.AddField(
            model_name='todomodel',
            name='time',
            field=models.TimeField(default=datetime.time(7, 42, 29, 893377)),
        ),
    ]
