# Generated by Django 4.2.6 on 2023-10-12 07:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_todomodel_datetime_todomodel_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='time',
            field=models.TimeField(default=datetime.time(7, 44, 36, 584738)),
        ),
    ]
