# Generated by Django 4.2.6 on 2023-10-12 07:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_todomodel_date_alter_todomodel_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='date',
            field=models.DateField(default=datetime.date(2023, 10, 12)),
        ),
        migrations.AlterField(
            model_name='todomodel',
            name='time',
            field=models.TimeField(default=datetime.time(7, 58, 40, 43352)),
        ),
    ]
