# Generated by Django 4.2.6 on 2023-10-13 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_todomodel_date_alter_todomodel_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todomodel',
            name='date',
        ),
        migrations.RemoveField(
            model_name='todomodel',
            name='time',
        ),
    ]
